version: '3'

services:
  db:
    container_name: marketplace_db
    image: postgres:alpine
    restart: always
    env_file:
      - marketplace.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  search:
    container_name: marketplace_search
    image: elasticsearch:6.8.8
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  web: &web
    container_name: marketplace_web
    build: ./backend
    command: gunicorn marketplace.wsgi:application --bind 0.0.0.0:8000 --workers=4 
    env_file:
      - marketplace.env
    expose:
      - 8000
    depends_on:
      - db
      - search
      - broker
      - celery_worker
    volumes:
      - staticfiles:/home/app/web/staticfiles/
      - mediafiles:/home/app/web/mediafiles/
  broker:
    container_name: marketplace_broker
    image: rabbitmq:3.7-alpine
  celery_worker:
    <<: *web
    container_name: marketplace_celery_worker
    command: celery -A marketplace worker --loglevel=INFO
    ports: []
    depends_on: 
      - broker
      - db
  nginx:
    container_name: marketplace_nginx
    image: nginx:mainline-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles/
      - mediafiles:/home/app/web/mediafiles/
    ports: 
      - "1337:80"
    depends_on:
      - web
volumes:
  postgres_data:
  elasticsearch:
  staticfiles:
  mediafiles:

