# Generated by Django 3.0.6 on 2020-05-27 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='avatars')),
                ('url', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(upload_to='thumbs/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('expected_price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('sold', models.BooleanField(default=False)),
                ('is_ticket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('num_offers', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.Category')),
                ('images', models.ManyToManyField(blank=True, to='main.ImageModel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel', models.CharField(choices=[('SR', 'SR Bhavan'), ('RP', 'Rana Pratap Bhavan'), ('GN', 'Gandhi Bhavan'), ('KR', 'Krishna Bhavan'), ('MR', 'Meera Bhavan')], max_length=2)),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('num_ratings', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('is_complete', models.BooleanField(default=False)),
                ('permission_level', models.SmallIntegerField(choices=[(0, 'Banned'), (1, 'Buyer'), (2, 'Seller'), (3, 'Admin')], default=2)),
                ('avatar', models.ManyToManyField(blank=True, to='main.Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='main.Product')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, 'Spam'), (2, 'Profanity'), (3, 'Refusal to Pay')])),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_given', to='main.Profile')),
                ('rating_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('answer', models.CharField(blank=True, max_length=600)),
                ('is_answered', models.BooleanField(default=False)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Product')),
            ],
            options={
                'verbose_name': 'Product QnA',
                'verbose_name_plural': 'Products QnA',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
                ('offerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.Profile'),
        ),
    ]
