# Generated by Django 2.1.5 on 2020-04-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('base_price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('STAT', 'Stationay'), ('MOVI', 'Movie Ticket'), ('GRUB', 'Grub Ticket'), ('ELEC', 'Electronics'), ('CLOT', 'Clothing'), ('OTHR', 'Other Utility')], max_length=4, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('is_ticket', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product.pics')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel', models.CharField(choices=[('SR', 'SR Bhavan'), ('RP', 'Rana Pratap Bhavan'), ('GN', 'Gandhi Bhavan'), ('KR', 'Krishna Bhavan'), ('MR', 'Meera Bhavan')], max_length=2)),
                ('room_no', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('no_of_ratings', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuesAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=600)),
                ('answer', models.CharField(max_length=600)),
                ('is_answered', models.BooleanField(default=True)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_questions', to='main.Profile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='RateUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_given', to='main.Profile')),
                ('rating_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_recieved', to='main.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='productbid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='productbid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='interested_buyers',
            field=models.ManyToManyField(blank=True, to='main.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_reported', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_items', to='main.Profile'),
        ),
    ]
