# Generated by Django 2.1.5 on 2020-04-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200420_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesandanswer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
