# Generated by Django 2.2.10 on 2020-04-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200421_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(upload_to='thumbs/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rating_by',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='rating_for',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='message',
            field=models.CharField(default='Sample Product report', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productqna',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.AddField(
            model_name='profilerating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_given', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='profilerating',
            name='rating_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_recieved', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='main.ImageModel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ImageModel'),
        ),
    ]
