# Generated by Django 2.2.10 on 2020-05-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200501_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission_level',
            field=models.SmallIntegerField(choices=[(0, 'Buyer'), (1, 'Buyer+Seller'), (2, 'Admin')], default=2),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, to='main.Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='main.Profile'),
        ),
    ]
