# Generated by Django 2.2.10 on 2020-05-21 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200510_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('message', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='room_no',
        ),
        migrations.AlterField(
            model_name='profilerating',
            name='rating_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='main.Profile'),
        ),
        migrations.DeleteModel(
            name='ProductBid',
        ),
        migrations.AddField(
            model_name='productoffer',
            name='offerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Product'),
        ),
    ]
