# Generated by Django 3.0.6 on 2020-05-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200523_2051'),
        ('main', '0025_auto_20200523_1810'),
    ]

    operations = [
    ]
