# Generated by Django 2.1.5 on 2020-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quesandanswer',
            name='answer',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
