# Generated by Django 2.1.5 on 2020-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
