# Generated by Django 2.1.5 on 2020-04-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200422_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, related_name='wishlist', to='main.Product')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
    ]
