# Generated by Django 2.1.5 on 2020-04-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200427_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='main.Profile'),
        ),
    ]
