# Generated by Django 2.1.5 on 2020-04-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200427_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='main.Product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
