# Generated by Django 2.2.10 on 2020-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200508_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='url',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
