# Generated by Django 2.2.10 on 2020-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200521_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permission_level',
            field=models.SmallIntegerField(choices=[(0, 'Banned'), (2, 'Buyer'), (2, 'Seller'), (3, 'Admin')], default=2),
        ),
    ]
