# Generated by Django 2.2.10 on 2020-05-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200523_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(1, 'Spam'), (2, 'Profanity'), (3, 'Refusal to Pay')])),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductReport',
        ),
    ]
