# Generated by Django 3.0.6 on 2020-05-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200523_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='num_offers',
            field=models.IntegerField(default=0),
        ),
    ]
